"""Stage-code accuracy harness.

Assignment section 13 grades "stage-code and disposition accuracy" at 15%.
"Accuracy" implies measurement, so this runs a labelled corpus through the real
guardrail and reports a score plus a confusion matrix, rather than asserting
correctness case by case.

**Scope, stated precisely.** This measures the *server-side guardrail*: given
what the extraction model reported, does the system store the correct
disposition? It does not measure the model's own extraction quality -- that is
covered by the console's Test Extraction tool against the table in
``gnani/postcall_extraction_config.md``. The two layers are complementary: the
model classifies, and this layer refuses to store an unsupported classification.

Run standalone to regenerate the report:

    python -m tests.test_disposition_accuracy
"""

from __future__ import annotations

import json
from collections import Counter
from datetime import date, timedelta
from pathlib import Path
from typing import Any

import pytest

from app.services.disposition import validate

FIXTURE = Path(__file__).parent / "fixtures" / "disposition_cases.json"
REPORT = Path(__file__).parent.parent / "docs" / "stage_code_accuracy.md"

#: The guardrail's job is to be right on every labelled case. Kept as an
#: explicit floor so a regression fails the build rather than quietly eroding.
MINIMUM_ACCURACY = 1.0


def load_corpus() -> tuple[date, list[dict[str, Any]]]:
    data = json.loads(FIXTURE.read_text(encoding="utf-8"))
    return date.fromisoformat(data["call_date"]), data["cases"]


def evaluate() -> dict[str, Any]:
    call_date, cases = load_corpus()
    rows: list[dict[str, Any]] = []

    for case in cases:
        result = validate(
            case["model_disposition"],
            raw_ptp_date=case["model_ptp_date"] or None,
            call_date=call_date,
        )

        expected_date = None
        if case["ptp_offset_days"] is not None:
            expected_date = call_date + timedelta(days=case["ptp_offset_days"])

        code_ok = str(result.stage_code) == case["expected_stage_code"]
        date_ok = result.ptp_date == expected_date

        rows.append(
            {
                "id": case["id"],
                "scenario": case["scenario"],
                "model_said": case["model_disposition"],
                "expected": case["expected_stage_code"],
                "actual": str(result.stage_code),
                "expected_date": expected_date,
                "actual_date": result.ptp_date,
                "code_ok": code_ok,
                "date_ok": date_ok,
                "passed": code_ok and date_ok,
                "corrected": case["model_disposition"] != case["expected_stage_code"],
                "adjustments": result.adjustments,
            }
        )

    total = len(rows)
    passed = sum(r["passed"] for r in rows)
    corrections = [r for r in rows if r["corrected"]]

    return {
        "call_date": call_date,
        "rows": rows,
        "total": total,
        "passed": passed,
        "accuracy": passed / total if total else 0.0,
        "corrections_expected": len(corrections),
        "corrections_made": sum(r["passed"] for r in corrections),
        "confusion": Counter(
            (r["expected"], r["actual"]) for r in rows if not r["code_ok"]
        ),
    }


def write_report(report: dict[str, Any]) -> None:
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Stage-code accuracy report",
        "",
        "Generated by `tests/test_disposition_accuracy.py` from the labelled",
        f"corpus in `tests/fixtures/disposition_cases.json` "
        f"({report['total']} cases, call date {report['call_date']}).",
        "",
        "**What this measures.** Given what the extraction model reported, does the",
        "system store the correct disposition? It scores the server-side guardrail,",
        "not the model's own extraction. Model-side accuracy is validated separately",
        "with the console's Test Extraction tool.",
        "",
        "## Result",
        "",
        f"- **Accuracy: {report['accuracy']:.1%}** ({report['passed']}/{report['total']})",
        f"- Cases where the model's label had to be corrected or refused: "
        f"**{report['corrections_expected']}**, of which "
        f"**{report['corrections_made']}** were handled correctly",
        "",
        "## Cases",
        "",
        "| # | Scenario | Model said | Stored | PTP date | ✓ |",
        "|---|---|---|---|---|---|",
    ]
    for row in report["rows"]:
        changed = " ⟳" if row["corrected"] else ""
        lines.append(
            f"| `{row['id']}` | {row['scenario']} | `{row['model_said']}`{changed} "
            f"| `{row['actual']}` | {row['actual_date'] or '—'} "
            f"| {'✅' if row['passed'] else '❌'} |"
        )

    lines += ["", "⟳ = the guardrail overrode the model's classification.", ""]

    if report["confusion"]:
        lines += ["## Confusion matrix (misclassifications only)", ""]
        lines += ["| Expected | Got | Count |", "|---|---|---|"]
        for (expected, actual), count in report["confusion"].most_common():
            lines.append(f"| `{expected}` | `{actual}` | {count} |")
    else:
        lines.append("No misclassifications: every labelled case resolved correctly.")

    lines += [
        "",
        "## Corrections the guardrail made",
        "",
    ]
    for row in report["rows"]:
        if row["corrected"] and row["adjustments"]:
            lines.append(f"- **{row['id']}** — {row['adjustments'][0]}")

    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def report() -> dict[str, Any]:
    result = evaluate()
    write_report(result)
    return result


def test_corpus_covers_the_mandatory_scenarios(report: dict[str, Any]) -> None:
    """Section 9 lists nine conversation scenarios; all must be represented."""
    ids = {row["id"] for row in report["rows"]}
    assert {f"S{n:02d}" for n in range(1, 10)} <= {i.split("-")[0] for i in ids}


def test_accuracy_meets_the_floor(report: dict[str, Any]) -> None:
    failures = [r for r in report["rows"] if not r["passed"]]
    detail = "\n".join(
        f"  {r['id']}: expected {r['expected']}/{r['expected_date']}, "
        f"got {r['actual']}/{r['actual_date']}"
        for r in failures
    )
    assert report["accuracy"] >= MINIMUM_ACCURACY, (
        f"accuracy {report['accuracy']:.1%} below floor "
        f"{MINIMUM_ACCURACY:.0%}\n{detail}"
    )


def test_the_guardrail_actually_corrects_things(report: dict[str, Any]) -> None:
    """A corpus that never exercises a correction proves nothing."""
    assert report["corrections_expected"] >= 8
    assert report["corrections_made"] == report["corrections_expected"]


def test_no_unsupported_promise_is_ever_stored(report: dict[str, Any]) -> None:
    """The central requirement of section 2, checked across the whole corpus."""
    for row in report["rows"]:
        if row["actual"].startswith("PTP_"):
            assert row["actual_date"] is not None, (
                f"{row['id']} stored {row['actual']} with no date"
            )


def test_report_is_written(report: dict[str, Any]) -> None:
    assert REPORT.exists()
    assert "Accuracy" in REPORT.read_text(encoding="utf-8")


if __name__ == "__main__":
    result = evaluate()
    write_report(result)
    print(f"accuracy: {result['accuracy']:.1%} ({result['passed']}/{result['total']})")
    print(f"corrections: {result['corrections_made']}/{result['corrections_expected']}")
    print(f"report: {REPORT}")
